feeds/urls.py
from django.urls import path
from . import views

app_name = 'feeds'

urlpatterns = [

    path('', views.get_feeds, name='feeds')
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [

    path('view/<slug:slug>/', views.ProfileDetail.as_view(), name='profile_detail'),
    path('suggestions/', views.SuggestionView.as_view(), name='suggestions'),
    path('follow/<uuid:profile_id>', views.ConnectRequest.as_view(), name='connect_request'),
    path('accept/<uuid:event_id>/<str:event_type>', views.ProcessRequest.as_view(), name='process_request'),

]

socialdj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('feeds/', include('feeds.urls')),
    path('notifications/', include('notifications.urls')),
    path('connections/', include('connections.urls')),

]

handler404 = 'socialdj.views.page_not_found'
# handler500 =


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

from django.contrib.auth.models import User
from .managers import ProfileManager, ConnectionManager
import uuid


class Profile(models.Model):
    """
    User profile
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)
    location = models.CharField(max_length=220, null=True, blank=True)
    bio = models.TextField(max_length=1000, blank=True)
    picture = models.ImageField(blank=True)
    mobile = models.CharField(max_length=10, null=True, blank=True)
    address = models.TextField(max_length=1000, null=True, blank=True)
    verified = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProfileManager()

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('profiles:profile_detail', args=[self.slug])

    @property
    def username(self):
        return self.user.username

    @property
    def full_name(self):
        return self.user.first_name + ' ' + self.user.last_name

    def set_active(self):
        if self.verified:
            self.is_active = True
            self.save()

    def connection_count(self):
        profiles = []
        cons = self.follows.all()
        for request in cons:
            if request.status == 'accepted':
                profiles.append(request.to_profile)
        return len(profiles)


class Connection(models.Model):
    """
    Follow model
    """

    STATUS_CHOICE = (
        ('requested', 'Requested'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    from_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='follows')
    to_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='followers')
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default='requested')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ConnectionManager()

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "Connection request from {} to {}".format(self.from_profile, self.to_profile)

    def accept(self):
        self.status = 'accepted'
        self.save()

    def reject(self):
        self.status = 'rejected'
        self.save()


Profile.add_to_class('following', models.ManyToManyField('self', through=Connection, related_name='followers'))

profiles/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views import View

from .models import Profile, Connection
from notifications.models import Activity, Notifications


class ProfileDetail(View):
    """
    A user profile detail view to land user to their profile page
    """

    template_name = 'profiles/profile.html'

    @method_decorator(login_required)
    def get(self, request, slug=None):
        profile = get_object_or_404(Profile, slug=slug)
        return render(self.request, self.template_name, context={'profile': profile})


class SuggestionView(View):
    """
     Build a recommendation system based on following criteria
     1. Number of common friends

     remember -
     while showing suggestions exclude the current user
     exclude those profiles which are already friends
     exclude those profiles to which there is already a friend request sent
     friend of friend can be friend
     """

    template_name = 'profiles/suggestions.html'

    def get(self, request):

        recommendations = set()

        # find friends of friend
        already_connected = self.request.user.profile.following.all()
        friends_of_friend = []
        for person in already_connected:
            for friend in person.following.all():
                if friend not in already_connected:
                    friends_of_friend.append(friend)

        # for testing only, there shouldn't be global search
        # every friend suggestion must be based on criteria, such as same school, same city
        # below code segment can be omitted
        global_profiles = Profile.objects.exclude(id__in=already_connected).exclude(user_id=self.request.user.id)
        for profile in global_profiles:
            recommendations.add(profile)

        for profile in friends_of_friend:
            recommendations.add(profile)

        return render(self.request, self.template_name, context={'profiles': recommendations})


class ConnectRequest(View):

    def get(self, request, profile_id):
        """
        Send connection request to other profile
        """

        # notifications are generated twice
        # but that needs to be handled in showing recommendations
        to_profile = Profile.objects.get(id=profile_id)
        conn, status = Connection.objects.get_or_create(from_profile=self.request.user.profile, to_profile=to_profile)

        # for notification
        activity = Activity().get_activity(activity='connection', subtype='request')
        actor = self.request.user
        description = actor.username + ' ' + activity.verb
        Notifications.objects.create(
            actor=actor.profile,
            recipient=to_profile,
            activity_type=activity,
            event_id=conn.id,
            description=description
        )
        messages.success(self.request, message='Connection request sent to {}'.format(to_profile.user.username))
        return HttpResponseRedirect(reverse('profiles:suggestions'))


class ProcessRequest(View):

    def get(self, request, event_id, event_type):

        cons = Connection.objects.get(id=event_id)
        if event_type == 'accept':
            cons.accept()
            activity = Activity().get_activity(activity='connection', subtype='accept')
            description = cons.to_profile.username + ' ' + activity.verb
            message = 'You accepted the connection request'
        else:
            cons.reject()
            activity = Activity().get_activity(activity='connection', subtype='reject')
            description = cons.to_profile.username + ' ' + activity.verb
            message = 'You rejected the connection request'

        # for notification
        Notifications.notify(
            actor=cons.to_profile,
            recipient=cons.from_profile,
            activity_type=activity,
            event_id=cons.id,
            description=description
        )
        messages.success(self.request, message=message)
        return HttpResponseRedirect(reverse('profiles:suggestions'))

profiles/templates/profiles/profile.html
{% extends 'inner_base.html' %}
{% load static %}

{% block title %}{{ request.user }} - SocialDJ{% endblock title %}


{% block content %}
    <h1>{{ name }}</h1>
    <div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
        <img class="me-3" src="/docs/5.0/assets/brand/bootstrap-logo-white.svg" alt="" width="48" height="38">
        <div class="lh-1">
            <h1 class="h6 mb-0 text-white lh-1">Hi {{ request.user.username }}</h1>
            {#            <small>Since 2011</small>#}
        </div>
    </div>

    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">Recent updates</h6>
        <div class="d-flex text-muted pt-3">
            <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#007bff"/>
                <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
            </svg>

            <p class="pb-3 mb-0 small lh-sm border-bottom">
                <strong class="d-block text-gray-dark">@username</strong>
                Some representative placeholder content, with some information about this user. Imagine this being
                some
                sort of status update, perhaps?
            </p>
        </div>
        <div class="d-flex text-muted pt-3">
            <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#e83e8c"/>
                <text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text>
            </svg>

            <p class="pb-3 mb-0 small lh-sm border-bottom">
                <strong class="d-block text-gray-dark">@username</strong>
                Some more representative placeholder content, related to this other user. Another status update,
                perhaps.
            </p>
        </div>
        <div class="d-flex text-muted pt-3">
            <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#6f42c1"/>
                <text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text>
            </svg>

            <p class="pb-3 mb-0 small lh-sm border-bottom">
                <strong class="d-block text-gray-dark">@username</strong>
                This user also gets some representative placeholder content. Maybe they did something interesting,
                and
                you really want to highlight this in the recent updates.
            </p>
        </div>
        <small class="d-block text-end mt-3">
            <a href="#">All updates</a>
        </small>
    </div>

    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">Suggestions</h6>
        <div class="d-flex text-muted pt-3">
            <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#007bff"/>
                <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
            </svg>

            <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                <div class="d-flex justify-content-between">
                    <strong class="text-gray-dark">Full Name</strong>
                    <a href="#">Follow</a>
                </div>
                <span class="d-block">@username</span>
            </div>
        </div>
        <div class="d-flex text-muted pt-3">
            <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#007bff"/>
                <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
            </svg>

            <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                <div class="d-flex justify-content-between">
                    <strong class="text-gray-dark">Full Name</strong>
                    <a href="#">Follow</a>
                </div>
                <span class="d-block">@username</span>
            </div>
        </div>
        <div class="d-flex text-muted pt-3">
            <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#007bff"/>
                <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
            </svg>

            <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                <div class="d-flex justify-content-between">
                    <strong class="text-gray-dark">Full Name</strong>
                    <a href="#">Follow</a>
                </div>
                <span class="d-block">@username</span>
            </div>
        </div>
        <small class="d-block text-end mt-3">
            <a href="#">All suggestions</a>
        </small>
    </div>
{% endblock %}

profiles/templates/profiles/suggestions.html
{% extends 'inner_base.html' %}
{% load static %}

{% block title %}{{ request.user }} - SocialDJ{% endblock title %}


{% block content %}
    <div class="d-flex align-items-center p-3 my-3 text-white bg-purple rounded shadow-sm">
        <img class="me-3" src="/docs/5.0/assets/brand/bootstrap-logo-white.svg" alt="" width="48" height="38">
        <div class="lh-1">
            <h1 class="h6 mb-0 text-white lh-1">Hi {{ request.user.username }}</h1>
            {#            <small>Since 2011</small>#}
        </div>
    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">Suggestions</h6>
        {% for profile in profiles %}
            <div class="d-flex text-muted pt-3">
                <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#007bff"/>
                    <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
                </svg>

                <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                    <div class="d-flex justify-content-between">
                        <strong class="text-gray-dark">{{ profile.full_name }}</strong>
                        <a href="{% url 'profiles:connect_request' profile.id %}">Follow</a>
                    </div>
                    <span class="d-block">{{ profile.user.username }}</span>
                </div>
            </div>
        {% endfor %}

        <small class="d-block text-end mt-3">
            <a href="#">All suggestions</a>
        </small>
    </div>
{% endblock %}