connections/urls.py
from django.urls import path
from . import views

app_name = 'connections'

urlpatterns = [
    path('', views.ConnectionsListView.as_view(), name='connections')
]

feeds/urls.py
from django.urls import path
from . import views

app_name = 'feeds'

urlpatterns = [

    path('', views.get_feeds, name='feeds')
]

notifications/urls.py
from django.urls import path
from . import views


app_name = 'notifications'

urlpatterns = [
    path('', views.NotificationsView.as_view(), name='notifications'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [

    path('view/<slug:slug>/', views.ProfileDetail.as_view(), name='profile_detail'),
    path('suggestions/', views.SuggestionView.as_view(), name='suggestions'),
    path('follow/<uuid:profile_id>', views.ConnectRequest.as_view(), name='connect_request'),
    path('accept/<uuid:event_id>/<str:event_type>', views.ProcessRequest.as_view(), name='process_request'),

]

socialdj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('feeds/', include('feeds.urls')),
    path('notifications/', include('notifications.urls')),
    path('connections/', include('connections.urls')),

]

handler404 = 'socialdj.views.page_not_found'
# handler500 =


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/nav.html
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">SocialDJ</a>
        <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="offcanvas"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        {#            make cliked link active#}
        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
                <a class="nav-link active" aria-current="page" href="{% url 'feeds:feeds' %}">Feeds</a>
                <a class="nav-link" href="{{ request.user.profile.get_absolute_url }}">Profile</a>
                <a class="nav-link" href="{% url 'connections:connections' %}">Connections</a>
                <span class="badge bg-light text-dark my-auto">{{ request.user.profile.connection_count }}</span>
                <a class="nav-link" href="#">Explore</a>
                <a class="nav-link" href="{% url 'profiles:suggestions' %}">Suggestions</a>
                <a class="nav-link" href="{% url 'notifications:notifications' %}">Notifications</a>
                <span class="badge bg-light text-dark align-text-bottom my-auto">{{ request.user.profile.notifications.count }}</span>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown"
                       aria-expanded="false">Settings</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                        <li><a class="dropdown-item" href="#">Profile Settings</a></li>
                        <li><a class="dropdown-item" href="#">Account Settings</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                    </ul>
                </li>
            </div>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>